# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Papaioannou Eleftherios
title: Undergraduate student of computer science and informatics.
email: lolopap21@gmail.com
website: https://github.com/LefterisIkaria/resume-cv/tree/gh-pages

# Social links
twitter_username: Gourou28474842
github_username:  LefterisIkaria
# dribbble_username: jekyll
facebook_username: Λευτερης Παπαϊωαννου
# flickr_username: jekyll
instagram_username: lefteris_ikaria
#linkedin_username: jameswgrant
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/me.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Lefteris and I'm an undergraduate studen at Ionian University at the department of computer science and informatics.
  I have some basic skills at programming and Databases and still learning about all the magic things I can do with enough practice.
# Projects Section
# projects_title: Projects

# Experience Section
experience_title: Seminars

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interest in programming some of my other interests and hobbies are:
   - Sports
   - Gaming

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
